config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  post 'users', to: 'users#create'
  get 'posts/new'
  post 'posts', to: 'posts#create'
  get 'posts/', to: 'posts#index'
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signin', to: 'sessions#delete'

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :create_remember_token
  has_many :posts
  has_secure_password

  private

  def create_remember_token
    token = SecureRandom.urlsafe_base64
    token_digest = Digest::SHA1.hexdigest token
    self.remember_token = token_digest
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper

  def set_current_user
    @current_user = User.find_by(email: params[:session][:email])
  end

  def sign_out
    @current_user = nil
    cookies.delete :remember_token
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include ApplicationHelper

  before_action :users_restricted_access, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if @post.save
      redirect_to root_path
    else
      render html: 'There was an error'
    end
  end

  def index
    @posts = Post.all
  end

  private

  def users_restricted_access
    redirect_to signin_path unless current_user
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :non_users_restricted_access, only: %i[new create]

  def new; end

  def create
    set_current_user
    if @current_user&.authenticate(params[:session][:password])
      sign_in
      redirect_to root_path
    else
      render html: 'Credentials provided are wrong'
    end
  end

  def delete
    sign_out
    redirect_to root_path
  end

  private

  def non_users_restricted_access
    redirect_to root_path if current_user
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include ApplicationHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @current_user = @user
      sign_in
      redirect_to root_path
    else
      render html: 'There was an error. Please try again'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(remember_token: cookies.permanent[:remember_token])
  end

  def sign_in
    @current_user.update(remember_token: set_remember_token)
    cookies.permanent[:remember_token] = @current_user.remember_token
  end

  def set_remember_token
    token = SecureRandom.urlsafe_base64
    Digest::SHA1.hexdigest token
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @posts.each do |p| %>
  <div style="border: 1px solid">
    <h2><%= p.title %></h2>
    <p><%= p.body %></p>
    <% if current_user %>
      <i>- <%= p.user.name %></i>
    <% end %>
  </div>
<% end %>

<ul>
  <% if current_user %>
    <li><%= link_to "Create new Post", posts_new_path %></li>
    <li><%= link_to "Sign Out", signin_path, method: 'delete' %></li>
  <% else %>
    <li><%= link_to "Sign In", signin_path %></li>
    <li><%= link_to "Sign Up", users_new_path %></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Create Post" %>
<% end %>

app/views/users/new.html.erb
<h1>User Sign Up</h1>
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create New User" %>
<% end %>